#!/bin/bash
# Prepare the repo so a session can build, lint and test immediately.
#
# Two things are needed and neither is in git:
#   - node_modules
#   - worker-configuration.d.ts, generated by `wrangler types` and listed under
#     "types" in tsconfig.json, so `tsc` fails without it
#
# Web sessions only: a local checkout is assumed to be set up already.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-.}"

# `install` rather than `ci` so a warm container can reuse what it already has.
npm install --no-audit --no-fund

# Offline and idempotent; reads wrangler.jsonc, writes the ambient Env types.
npx wrangler types >/dev/null

echo "Ready: dependencies installed, worker types generated."
